#导入Seurat对象
load("sce.Rdata")
#添加样本信息
meta <-data.frame(Sample=substr(colnames(sce),1,4))
rownames(meta) <- colnames(sce)
sce <- AddMetaData(sce,metadata = meta,col.name = "Sample")
seurat_obj = sce
library(Seurat)
library(tidyverse)
library(cowplot)
library(patchwork)
library(WGCNA)
library(hdWGCNA)
theme_set(theme_cowplot())
set.seed(12345)
p <- DimPlot(seurat_obj,group.by='Celltype',label=T)
seurat_obj <- SetupForWGCNA(seurat_obj,gene_select="fraction",fraction=0.05,wgcna_name = "tutorial")
length(seurat_obj@misc$tutorial$wgcna_genes)
[1] 13560
seurat_obj <- MetacellsByGroups(seurat_obj = seurat_obj,group.by = c("Celltype","Sample"),k=25,max_shared=10,ident.group = 'Celltype',reduction='harmony')
seurat_obj <- NormalizeMetacells(seurat_obj)
seurat_obj <- ScaleMetacells(seurat_obj,features=VariableFeatures(seurat_obj))
#seurat_obj <- FindVariableFeatures(seurat_obj)
seurat_obj <- RunPCAMetacells(seurat_obj,features=VariableFeatures(seurat_obj))
seurat_obj <- RunHarmonyMetacells(seurat_obj,group.by.vars='Sample')
seurat_obj <- RunUMAPMetacells(seurat_obj,reduction='harmony',dims=1:15)
p1 <- DimPlotMetacells(seurat_obj,group.by='Celltype')+ggtitle("Cell Type")
p2 <- DimPlotMetacells(seurat_obj,group.by='Sample')+ggtitle("Sample")
seurat_obj <- SetDatExpr(seurat_obj,group_name = c("Normal","Tumor"),group.by = 'Celltype',assay='RNA',slot='data')
seurat_obj <- TestSoftPowers(seurat_obj,networkType = 'signed')
plot_list <- PlotSoftPowers(seurat_obj)
wrap_plots(plot_list,ncol=2)
power_table <- GetPowerTable(seurat_obj)
head(power_table)
seurat_obj <- ConstructNetwork(seurat_obj,soft_power = 12,SetDatExpr=F,tom_name = 'HGSC')
PlotDendrogram(seurat_obj,main='HGSC hdWGCNA Dendrogram')
seurat_obj@misc$tutorial$wgcna_modules %>% head
#write.table(seurat_obj@misc$tutorial$wgcna_modules,file="module_gene.txt",quote=F,row.names = F,col.names = T,sep="\t")
table(seurat_obj@misc$tutorial$wgcna_modules$module)
seurat_obj <- ScaleData(seurat_obj,features=VariableFeatures(seurat_obj))
seurat_obj <- ModuleEigengenes(seurat_obj,group.by.vars = "Sample")
hMEs <- GetMEs(seurat_obj)
head(hMEs)
seurat_obj <- ModuleConnectivity(seurat_obj,group.by = 'Celltype',group_name = c("Normal","Tumor"))
p <- PlotKMEs(seurat_obj,ncol=5)
modules <- GetModules(seurat_obj)
head(modules[,1:6])
hub_df <- GetHubGenes(seurat_obj,n_hubs = 10)
head(hub_df)
#write.table(hub_df,file="hub_gene.txt",quote=F,row.names = F,col.names = T,sep="\t")
saveRDS(seurat_obj,file='HGSC_hdWGCNA_object.rds')
seurat_obj <- ModuleExprScore(seurat_obj,n_genes = 25,method = 'Seurat')
plot_list <- ModuleFeaturePlot(seurat_obj,features = 'hMEs',order=T)
wrap_plots(plot_list,ncol=6)
plot_list <- ModuleFeaturePlot(seurat_obj,features = 'scores',order='shuffle',ucell=T)
wrap_plots(plot_list,ncol=6)
ModuleCorrelogram(seurat_obj)
MEs <-GetMEs(seurat_obj,harmonized = T)
mods <- colnames(MEs)
mods <- mods[mods !='grey']
seurat_obj@meta.data <- cbind(seurat_obj@meta.data,MEs)
p <- DotPlot(seurat_obj,features = mods,group.by = 'Celltype')
p <- p+coord_flip()+RotatedAxis()+scale_color_gradient2(high='red',mid='grey95',low='blue')